## 38단계: 형상 변환 함수

> .

### 38.1 reshape 함수 구현

<img src="images/그림 38-1.png" width=600/>

In [1]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.reshape(x, (6,))
print(y)

[1 2 3 4 5 6]


In [2]:
# dezero/functions.py

from dezero import Function

class Reshape(Function):
    def __init__(self, shape):
        self.shape = shape

    def forward(self, x):
        self.x_shape = x.shape
        y = np.reshape(x, self.shape)
        return y

    def backward(self, gy):
        return np.reshape(gy, self.x_shape)


from dezero.core import as_variable

def reshape(x, shape):
    if x.shape == shape:
        return as_variable(x)
    return Reshape(shape)(x)

In [3]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.reshape(x, (6,))
y.backward(retain_grad=True)
print(x.grad)

Variable([[1 1 1]
          [1 1 1]])


<img src="images/그림 38-2.png" width=400/>

### 38.2 Variable에서 reshape 사용하기

In [4]:
x = np.random.rand(1, 2, 3)

y = x.reshape((2, 3))  # 튜플로 받기
y = x.reshape([2, 3])  # 리스트로 받기
y = x.reshape(2, 3)  # 인수를 그대로(풀어서) 받기

In [5]:
# dezero/core.py

import dezero

class Variable:
    ...
    
    def reshape(self, *shape):
        if len(shape) == 1 and isinstance(shape[0], (list, tuple)):
            shape = shape[0]
        return dezero.functions.reshape(self, shape)

In [6]:
from dezero import Variable

x = Variable(np.random.randn(1, 2, 3))
y = x.reshape((2, 3))
y = x.reshape(2, 3)

### 38.3 행렬의 전치

<img src="images/그림 38-3.png" width=500/>

In [7]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.transpose(x)
print(y)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
# dezero/functions.py

class Transpose(Function):
    def forward(self, x):
        y = np.transpose(x)
        return y

    def backward(self, gy):
        gx = transpose(gy)
        return gx

def transpose(x):
    return Transpose()(x)

In [9]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.transpose(x)
y.backward()
print(x.grad)

Variable([[1 1 1]
          [1 1 1]])


In [10]:
class Variable:
    ...
    
    def transpose(self):
        return dezero.functions.transpose(self)
    
    @property
    def T(self):
        return dezero.functions.transpose(self)

In [11]:
from dezero import Variable

x = Variable(np.random.rand(2, 3))
y = x.transpose()
y = x.T
print(y.shape)

(3, 2)


### 38.4 [보충] 실제 transpose 함수

<img src="images/그림 38-4.png" width=450/>