## 37단계: 텐서를 다루다

> .

### 37.1 원소별 계산

In [1]:
import numpy as np
import dezero.functions as F
from dezero import Variable

x = Variable(np.array(1.0))
y = F.sin(x)
print(y)

Variable(0.8414709848078965)


In [2]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
y = F.sin(x)
print(y)

Variable([[ 0.84147098  0.90929743  0.14112001]
          [-0.7568025  -0.95892427 -0.2794155 ]])


In [3]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
c = Variable(np.array([[10, 20, 30], [40, 50, 60]]))
y = x + c
print(y)

Variable([[11 22 33]
          [44 55 66]])


### 37.2 텐서 사용 시의 역전파

<img src="images/그림 37-1.png" width=500/>

In [4]:
x = Variable(np.array([[1, 2, 3], [4, 5, 6]]))
c = Variable(np.array([[10, 20, 30], [40, 50, 60]]))
t = x + c
y = F.sum(t)

y.backward(retain_grad=True)
print(y.grad)
print(t.grad)
print(x.grad)
print(c.grad)

Variable(1)
Variable([[1 1 1]
          [1 1 1]])
Variable([[1 1 1]
          [1 1 1]])
Variable([[1 1 1]
          [1 1 1]])
